# Generated by Django 5.2.1 on 2025-05-09 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('wage', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=7)),
                ('users', models.ManyToManyField(related_name='work_packages', to='TubitakPlannerApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.IntegerField()),
                ('end_date', models.IntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=7)),
                ('users', models.ManyToManyField(related_name='tasks', to='TubitakPlannerApp.user')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='TubitakPlannerApp.workpackage')),
            ],
        ),
    ]
