# Generated by Django 5.2.1 on 2025-05-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
            ],
        ),
    ]
