# Generated by Django 5.2.1 on 2025-05-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='TubitakPlannerApp.workpackage')),
            ],
        ),
    ]
