# Generated by Django 5.2.1 on 2025-05-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0003_deliverable'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
