# Generated by Django 5.2 on 2025-05-30 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0004_deliverable_deadline_deliverable_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverable',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='deliverable',
            name='description',
        ),
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('contribution', models.DecimalField(decimal_places=2, max_digits=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to='TubitakPlannerApp.user')),
                ('work_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_entries', to='TubitakPlannerApp.workpackage')),
            ],
            options={
                'unique_together': {('work_package', 'user', 'month')},
            },
        ),
    ]
