# Generated by Django 5.2 on 2025-05-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0005_remove_deliverable_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverable',
            name='deadline',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverable',
            name='description',
            field=models.TextField(default='dummydesc'),
            preserve_default=False,
        ),
    ]
