# Generated by Django 5.2.1 on 2025-05-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0006_deliverable_deadline_deliverable_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverable',
            name='deadline',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
