# Generated by Django 5.2.2 on 2025-06-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0007_alter_deliverable_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workpackage',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
