# Generated by Django 4.2.16 on 2025-07-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0009_projectleaduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectleaduser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
