# Generated by Django 5.2.4 on 2025-08-12 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TubitakPlannerApp', '0011_project_created_at_project_owner_workpackage_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='project_lead',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
